### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by luketlancaster** [code-for-nashville/open-data-accountability#21]
Not an 'issue' per-se, but if you would like access to the Heroku app/repo shoot me your email address and I'll add you as a collaborator. Apologies for not thinking about this earlier.

My address is luketlancaster@gmail.com, feel free to email there or just leave a comment on this thread.

Also, as this is one of my first projects like this, let me know if this isn't an appropriate place for this.

**Comment by jchapin** [comment]
@luketlancaster the CfN Heroku account is webmaster@codefornashville.org. We would be happy to pick up collaborator status and owner status to pay the bills if needed. Copying @neolytics and @jcockhren on this issue / thread.

**Comment by luketlancaster** [comment]
Just added that address as a collaborator, and transferred ownership. Once accepted this issue can be closed. Happy to continue contributing, just seems like it should be owned by the org and not me :smile:

**Comment by luketlancaster** [comment]
Ownership has been transferred, so I'm closing this issue 👍
