### ISSUE TITLE
Ability to select different cities for comparison

### ISSUE THREAD

**Issue by JamesNix** [code-for-nashville/open-data-accountability#8]
Drop down or some similar selector in the place of "Honolulu" in top left corner that would allow user to from other available city data sets.

**Comment by luketlancaster** [comment]
Was thinking the same thing, there should be one there with the sets I could find that fit into the current url syntax. The list can be found in the application_helper.

Haven't pushed these changes to Heroku, if you wanna look over them and let me know if they look good that'd be super helpful.

My current view:
<img width="1280" alt="watchdawgs" src="https://cloud.githubusercontent.com/assets/8376505/8712953/45cc7c78-2b28-11e5-9b20-cc805a5c06e7.png">

**Comment by luketlancaster** [comment]
@code-for-nashville/openaccountability if all agree, I'll close this and push it up to Heroku.

**Comment by jchapin** [comment]
@luketlancaster, I think this has been satisfied. Push it on up.

**Comment by jchapin** [comment]
Speaking of which... Salt n' Pepa's "Push It" is playing on the sound system at Red Bicycle right now... Push it real good..

**Comment by luketlancaster** [comment]
Just pushed. Marking as closed.
